### ISSUE TITLE
Mobie project validation fails

### ISSUE THREAD

**Issue by jhennies** [jhennies/CebraEM#27]
With a new installation ```init_project ... -m ...``` runs into a json validation error (see below). 

The json for the mask is validated against https://raw.githubusercontent.com/mobie/mobie.github.io/master/schema/view.schema.json which is apparently not compatible with the mobie version supported here. 

The best solution would be to update the mobie version. 

```
Traceback (most recent call last):
  File "/home/hennies/miniconda3/envs/cebra-em-all-env/lib/python3.9/site-packages/mobie/validation/metadata.py", line 196, in validate_view_metadata
    validate_with_schema(view, "view")
  File "/home/hennies/miniconda3/envs/cebra-em-all-env/lib/python3.9/site-packages/mobie/validation/utils.py", line 56, in validate_with_schema
    jsonschema.validate(instance=metadata, schema=schema)
  File "/home/hennies/miniconda3/envs/cebra-em-all-env/lib/python3.9/site-packages/jsonschema/validators.py", line 1121, in validate
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('tables' was unexpected)

Failed validating 'additionalProperties' in schema[1]['properties']['segmentationDisplay']:
    {'additionalProperties': False,
     'description': '',
     'properties': {'additionalTables': {'$ref': '#/definitions/additionalTables'},
                    'boundaryThickness': {'description': 'Thickness of the '
                                                         'boundary masks. '
                                                         'Only used if '
                                                         'showAsBoundaries '
                                                         'is true.',
                                          'type': 'number'},
                    'colorByColumn': {'$ref': '#/definitions/name',
                                      'description': 'Name of table column '
                                                     'that is used for '
                                                     'coloring. By default '
                                                     "the 'label_id' "
                                                     'column is used.'},
                    'lut': {'$ref': '#/definitions/lut'},
                    'name': {'$ref': '#/definitions/name',
                             'description': 'Name of this segmentation '
                                            'display.'},
                    'opacity': {'$ref': '#/definitions/opacity'},
                    'opacityNotSelected': {'$ref': '#/definitions/opacityNotSelected'},
                    'randomColorSeed': {'description': 'Random seed for '
                                                       'the random color '
                                                       'lut (e.g. glasbey) '
                                                       'to reproduce the '
                                                       'exact colors of '
                                                       'the view. '
                                                       '(Optional)',
                                        'type': 'number'},
                    'resolution3dView': {'description': 'Resolution used '
                                                        'for the 3d '
                                                        'viewer, in '
                                                        'physical units. '
                                                        'Only relevant if '
                                                        "'showSelectedSegmentsIn3d' "
                                                        'is true. Will be '
                                                        'determined '
                                                        'automatically if '
                                                        'not specified.',
                                         'items': {'exclusiveMinimum': 0,
                                                   'type': 'number'},
                                         'maxItems': 3,
                                         'minItems': 3,
                                         'type': 'array'},
                    'scatterPlotAxes': {'$ref': '#/definitions/scatterPlotAxes'},
                    'selectedSegmentIds': {'description': 'List of '
                                                          'selected '
                                                          'segment ids, '
                                                          'each of the '
                                                          'form '
                                                          'sourceName;timePoint;label_id',
                                           'items': {'pattern': '^[^; '
                                                                '\\/]+;\\d+;\\d+$',
                                                     'type': 'string'},
                                           'type': 'array'},
                    'selectionColor': {'$ref': '#/definitions/selectionColor'},
                    'showAsBoundaries': {'description': 'Show boundary '
                                                        'mask instead of '
                                                        'segment masks. '
                                                        'Default is false.',
                                         'type': 'boolean'},
                    'showScatterPlot': {'description': 'Whether to show '
                                                       'the scatter plot. '
                                                       'The default is '
                                                       "'false', i.e. if "
                                                       'this property is '
                                                       'not present the '
                                                       'scatter plot '
                                                       'should not be '
                                                       'shown. If it is '
                                                       "'true' then "
                                                       "'scatterPlotAxes' "
                                                       'must be given.',
                                        'type': 'boolean'},
                    'showSelectedSegmentsIn3d': {'description': 'Whether '
                                                                'to show '
                                                                'the '
                                                                'selected '
                                                                'segments '
                                                                'in the 3d '
                                                                'viewer.',
                                                 'type': 'boolean'},
                    'showTable': {'description': 'Show the table GUI '
                                                 'element. Default is true '
                                                 '(if the display has a '
                                                 'table).',
                                  'type': 'boolean'},
                    'sources': {'description': 'The segmentation sources '
                                               'that are part of this '
                                               'display group. Multiple '
                                               'sources should be moved '
                                               'apart spatially with '
                                               'source transform(s), e.g. '
                                               'grid, otherwise they will '
                                               'not be correctly displayed '
                                               'in the viewer.',
                                'items': {'$ref': '#/definitions/name'},
                                'minItems': 1,
                                'type': 'array'},
                    'valueLimits': {'$ref': '#/definitions/valueLimits'},
                    'visible': {'description': 'Are the sources of this '
                                               'display visible? Default '
                                               'is true.',
                                'type': 'boolean'}},
     'required': ['opacity', 'lut', 'name', 'sources'],
     'type': 'object'}

On instance['segmentationDisplay']:
    {'lut': 'glasbey',
     'name': 'em-mask',
     'opacity': 0.5,
     'sources': ['em-mask'],
     'tables': ['default.tsv']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hennies/miniconda3/envs/cebra-em-all-env/bin/init_project.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/g/schwab/hennies/src/github/jhennies/CebraEM/cebra-em/bin/init_project.py", line 65, in <module>
    init_project(
  File "/g/schwab/hennies/src/github/jhennies/CebraEM/cebra-em-core/cebra_em_core/cebra_em_project.py", line 250, in init_project
    init_mobie_dataset(project_path=project_path, verbose=verbose)
  File "/g/schwab/hennies/src/github/jhennies/CebraEM/cebra-em-core/cebra_em_core/cebra_em_project.py", line 139, in init_mobie_dataset
    init_mask(
  File "/g/schwab/hennies/src/github/jhennies/CebraEM/cebra-em-core/cebra_em_core/dataset/mobie_utils.py", line 411, in init_mask
    add_source_to_dataset(
  File "/home/hennies/miniconda3/envs/cebra-em-all-env/lib/python3.9/site-packages/mobie/metadata/source_metadata.py", line 251, in add_source_to_dataset
    validate_view_metadata(view)
  File "/home/hennies/miniconda3/envs/cebra-em-all-env/lib/python3.9/site-packages/mobie/validation/metadata.py", line 199, in validate_view_metadata
    assert_true(False, msg)
  File "/home/hennies/miniconda3/envs/cebra-em-all-env/lib/python3.9/site-packages/mobie/validation/utils.py", line 77, in _assert_true
    raise ValueError(msg)
ValueError: Additional properties are not allowed ('tables' was unexpected)

Failed validating 'additionalProperties' in schema[1]['properties']['segmentationDisplay']:
    {'additionalProperties': False,
     'description': '',
     'properties': {'additionalTables': {'$ref': '#/definitions/additionalTables'},
                    'boundaryThickness': {'description': 'Thickness of the '
                                                         'boundary masks. '
                                                         'Only used if '
                                                         'showAsBoundaries '
                                                         'is true.',
                                          'type': 'number'},
                    'colorByColumn': {'$ref': '#/definitions/name',
                                      'description': 'Name of table column '
                                                     'that is used for '
                                                     'coloring. By default '
                                                     "the 'label_id' "
                                                     'column is used.'},
                    'lut': {'$ref': '#/definitions/lut'},
                    'name': {'$ref': '#/definitions/name',
                             'description': 'Name of this segmentation '
                                            'display.'},
                    'opacity': {'$ref': '#/definitions/opacity'},
                    'opacityNotSelected': {'$ref': '#/definitions/opacityNotSelected'},
                    'randomColorSeed': {'description': 'Random seed for '
                                                       'the random color '
                                                       'lut (e.g. glasbey) '
                                                       'to reproduce the '
                                                       'exact colors of '
                                                       'the view. '
                                                       '(Optional)',
                                        'type': 'number'},
                    'resolution3dView': {'description': 'Resolution used '
                                                        'for the 3d '
                                                        'viewer, in '
                                                        'physical units. '
                                                        'Only relevant if '
                                                        "'showSelectedSegmentsIn3d' "
                                                        'is true. Will be '
                                                        'determined '
                                                        'automatically if '
                                                        'not specified.',
                                         'items': {'exclusiveMinimum': 0,
                                                   'type': 'number'},
                                         'maxItems': 3,
                                         'minItems': 3,
                                         'type': 'array'},
                    'scatterPlotAxes': {'$ref': '#/definitions/scatterPlotAxes'},
                    'selectedSegmentIds': {'description': 'List of '
                                                          'selected '
                                                          'segment ids, '
                                                          'each of the '
                                                          'form '
                                                          'sourceName;timePoint;label_id',
                                           'items': {'pattern': '^[^; '
                                                                '\\/]+;\\d+;\\d+$',
                                                     'type': 'string'},
                                           'type': 'array'},
                    'selectionColor': {'$ref': '#/definitions/selectionColor'},
                    'showAsBoundaries': {'description': 'Show boundary '
                                                        'mask instead of '
                                                        'segment masks. '
                                                        'Default is false.',
                                         'type': 'boolean'},
                    'showScatterPlot': {'description': 'Whether to show '
                                                       'the scatter plot. '
                                                       'The default is '
                                                       "'false', i.e. if "
                                                       'this property is '
                                                       'not present the '
                                                       'scatter plot '
                                                       'should not be '
                                                       'shown. If it is '
                                                       "'true' then "
                                                       "'scatterPlotAxes' "
                                                       'must be given.',
                                        'type': 'boolean'},
                    'showSelectedSegmentsIn3d': {'description': 'Whether '
                                                                'to show '
                                                                'the '
                                                                'selected '
                                                                'segments '
                                                                'in the 3d '
                                                                'viewer.',
                                                 'type': 'boolean'},
                    'showTable': {'description': 'Show the table GUI '
                                                 'element. Default is true '
                                                 '(if the display has a '
                                                 'table).',
                                  'type': 'boolean'},
                    'sources': {'description': 'The segmentation sources '
                                               'that are part of this '
                                               'display group. Multiple '
                                               'sources should be moved '
                                               'apart spatially with '
                                               'source transform(s), e.g. '
                                               'grid, otherwise they will '
                                               'not be correctly displayed '
                                               'in the viewer.',
                                'items': {'$ref': '#/definitions/name'},
                                'minItems': 1,
                                'type': 'array'},
                    'valueLimits': {'$ref': '#/definitions/valueLimits'},
                    'visible': {'description': 'Are the sources of this '
                                               'display visible? Default '
                                               'is true.',
                                'type': 'boolean'}},
     'required': ['opacity', 'lut', 'name', 'sources'],
     'type': 'object'}

On instance['segmentationDisplay']:
    {'lut': 'glasbey',
     'name': 'em-mask',
     'opacity': 0.5,
     'sources': ['em-mask'],
     'tables': ['default.tsv']}
```

**Comment by jhennies** [comment]
fixed with merge #66 where [mobie-utils](https://github.com/mobie/mobie-utils-python) is not used anymore
