### ISSUE TITLE
Python KeyError at final segmentation: Manually initialized 'segmentations' in config file

### ISSUE THREAD

**Issue by mrheinnecker** [jhennies/CebraEM#33]
I ran into the following issue while running: run.py -t nuc_it00  (running nucleus segmentation after annotation of gt_cube)

The prompted Error is:
Traceback (most recent call last):
  File "/home/rheinnec/miniconda3/envs/cebra-em-env/bin/run.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/rheinnec/repos/CebraEM/cebra-em/bin/run.py", line 325, in <module>
    run(
  File "/home/rheinnec/repos/CebraEM/cebra-em/bin/run.py", line 211, in run
    if bm not in config_seg['segmentations'].keys():
KeyError: 'segmentations'

I saw that in **config/config_nuc_it00.json** there is no 'segmentations' entry, which I think the script is looking for. 
I think actually this is only needed to check if it is already there and otherwise it will be created. So I included a dummy-segmentation entry in the config file (or just copied and renamed another dictonary entry):

"segmentations": {
    "cpuxxxs": 1
}

After that the segmentation started and is currently running.
I am not sure if it is again on my side that there is no entry, but also creating another iteration for nuc (nuc_it01) with init_segmentation.py and linking the ground thruths with link_gt.py did not add an 'segmentations' entry to the config. Maybe i am missing another function call?

Best wishes!
Marco

**Comment by mzugravu** [comment]
@mrheinnecker 

Hi Marco,
I was wondering if you managed to complete the whole CebraEM workflow. I am encountering some issues. I would be really grateful if you could let me know.

Best wishes, 
Bianca

**Comment by mrheinnecker** [comment]
Yes i managed to run it.
